name: Ruby

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Daily job that runs at 7AM UTC to test with the newest sorbet.
  schedule:
    - cron: '0 7 * * *'

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: .ruby-version
        bundler-cache: true # 'bundle install' and cache gems
    - name: Run tests
      run: bundle exec rake
